---
glob: "**/*.erb"
EnableDefaultLinters: true
linters:
  HardCodedString:
    enabled: true
    exclude:
      - "*.erb"
  ErbSafety:
    enabled: true
    exclude:
      - "*.erb"
    better_html_config: .better-html.yml
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Style/Semicolon:
        Enabled: true
        AllowAsExpressionSeparator: true
      Lint/UselessAssignment:
        Enabled: false
